# Generated by Django 2.0 on 2017-12-27 21:44

import datetime
from django.db import migrations, models
import news.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', tinymce.models.HTMLField(verbose_name='Body')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models._news_images, verbose_name='Headline image')),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 27, 15, 44, 36, 555082), null=True, verbose_name='Date published')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News items',
            },
        ),
    ]
