# Generated by Django 2.2.18 on 2021-02-16 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date_published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date published'),
        ),
    ]
