# Generated by Django 2.0 on 2017-12-27 15:27

import autoslug.fields
import dash.helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20170311_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardworkspace',
            old_name='is_clonable',
            new_name='is_cloneable',
        ),
        migrations.AlterField(
            model_name='dashboardworkspace',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=dash.helpers.slugify_workspace, unique=True, verbose_name='Slug'),
        ),
    ]
