# Generated by Django 2.2.18 on 2021-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('external', models.BooleanField(default=False, verbose_name='External')),
                ('image', models.CharField(blank=True, choices=[('', '---------'), ('icon-film', 'Film'), ('icon-calendar', 'Calendar'), ('icon-book', 'Book'), ('icon-music', 'Music'), ('icon-picture', 'Picture'), ('icon-star', 'Star'), ('icon-thumbs-up', 'Thumbs-up'), ('icon-plane', 'Plane'), ('icon-road', 'Road'), ('icon-camera', 'Camera'), ('icon-download', 'Download'), ('icon-info-sign', 'Info'), ('icon-shopping-cart', 'Shopping cart'), ('icon-wrench', 'Wrench'), ('icon-lock', 'Lock'), ('icon-heart', 'Heart'), ('icon-question-sign', 'Question'), ('icon-headphones', 'Headphones'), ('icon-gift', 'Gift'), ('icon-comment', 'Comment'), ('icon-bell', 'Bell'), ('icon-search', 'Search'), ('icon-map-marker', 'Map marker'), ('icon-globe', 'Globe'), ('icon-pencil', 'Pensil'), ('icon-tasks', 'Tasks')], max_length=255, null=True, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
            },
        ),
    ]
